id: excel-custom-functions-example
name: New Function
description: Describe the operation the function will perform
host: EXCEL
api_set:
    CustomFunctionsRuntime: 1.1
script:
    content: |
        /**
         * Provides an example of creating an custom function. 
         * @customfunction
         * @param {number} radius
         * @returns The volume of the sphere.
         */
        function exampleFunction(radius) {
          return Math.pow(radius, 3) * 4 * Math.PI / 3;
        }
    language: typescript
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js
    core-js@2.4.1/client/core.min.js
